language: php

services:
  - docker

before_script:
  - docker build -t mn-monolog:latest .
  - docker run -v `pwd`:/mn-monolog mn-monolog:latest composer install --prefer-dist

cache:
  directories:
    - vendor

script: docker run -v `pwd`:/mn-monolog mn-monolog:latest composer test


